let data2 = [
    {
        id: 0,
        title: "the child",
        imgUrl: "/img/THE_CHILD.png",
        size: "sixth Scale Figure",
        text: "The Child",
        price: 380,
        brand: "Star Wars",
        character: "The Child.Grogu",
        manufacturer: "Sideshow Collectibles",
        type: "Figure>Life-Size Figure",
        genre: "Sci-fi,Pop Culture",
        artists: "Legacy Effects (Sculpt) (Mold and Cast) (Paint) (Cut and Sew) (Development) (Design), The Sideshow Design and Development Team (Development) (Design)",
        imgProduct1: "/img/THE_CHILD1.jpg",
        imgProduct2: "/img/THE_CHILD2.jpg",
        imgProduct3: "/img/THE_CHILD3.jpg",
        imgProduct4: "/img/THE_CHILD4.jpg",
        imgProduct5: "/img/THE_CHILD5.jpg",
        preview: "I would like to see the baby. Sideshow presents The Child Life-Size Figure, created in partnership with Legacy Effects to bring you the galaxys most sought-after bounty. Lovingly referred to by audiences as Baby Yoda, the mysterious alien known as The Child or Grogu has quickly become the breakout fan-favorite of Star Wars™: The Mandalorian on Disney+. Now eager collectors can become a clan of two and bring home the asset as an incredible 1:1 scale Star Wars collectible, no tracking fob needed.The Child Life-Size Figure measures 16.5” tall, standing on a simple ship deck base that lets this adorable alien steal all of the focus- along with the Mandalorians ship parts. Inspired by its unique onscreen appearance, this mixed media statue features a tan fabric coat swaddling The Child as it gazes up with charming wide eyes, hiding the silver shift knob from the Razor Crest™ in its right hand. Every inch of this incredibly lifelike figure has been meticulously detailed to recreate everything that Star Wars fans love about the young alien, from the fuzz on its wrinkled head to its irresistible pout, all the way down to its tiny, toddling feet. Fans looking to bring home The Mandalorian collectibles need look no further- bounty hunting is a complicated profession but collecting the galaxys cutest alien has never been easier!Secure the asset for your Star Wars collectible figures and bring home The Child Life-Size Figure today."
    },
    {
        id: 1,
        title: "ahsoka tano",
        imgUrl: "/img/AHSOKA_TANO.png",
        size: "sixth Scale Figure",
        price: 255,
        brand: "Star Wars",
        character: "The Child.Grogu",
        manufacturer: "Sideshow Collectibles",
        type: "Figure>Life-Size Figure",
        genre: "Sci-fi,Pop Culture",
        artists: "Legacy Effects (Sculpt) (Mold and Cast) (Paint) (Cut and Sew) (Development) (Design), The Sideshow Design and Development Team (Development) (Design)",
        imgProduct1: "/img/AHSOKA_TANO1.jpg",
        imgProduct2: "/img/AHSOKA_TANO2.jpg",
        imgProduct3: "/img/AHSOKA_TANO3.jpg",
        imgProduct4: "/img/AHSOKA_TANO4.jpg",
        imgProduct5: "/img/AHSOKA_TANO5.jpg",
        preview: "Ahsoka Tano, a Togruta™, was the Padawan™ learner to Anakin Skywalker™ and a hero of the Clone Wars. Alongside Anakin, she grew from headstrong student into a mature leader. But her destiny laid along a different path than the Jedi™… Sideshow and Hot Toys is pleased to further expand the Star Wars: The Clone Wars collectible series by introducing a dynamic sixth scale interpretation of the beloved character Ahsoka Tano, representing her appearance in the final season of the acclaimed animated series! The greatly detailed Ahsoka Tano collectible figure is specially crafted with authentic styling featuring a skillfully crafted head sculpt with stunning likeness and articulated head-tails, specialized body to portray Ahsoka's physique, finely tailored outfit and armor pieces, Ahsoka's iconic lightsabers, a cloak, and a display base! Enrich your Star Wars collectibles display with this amazing Ahsoka Tano Sixth Scale Collectible Figure today!"
    },
    {
        id: 2,
        title: "anakin skywaker",
        imgUrl: "/img/ANAKIN_SKYWAKER.png",
        size: "Sixth Scale Figure",
        price: 265,
        brand: "Star Wars",
        character: "Anakin Skywalker",
        manufacturer: "Hot Toys",
        type: "Action Figure>Sixth Scale Figure",
        genre: "Animation, Sci-fi Pop, Culture",
        artists: "JC. Hong (Head Paint) (Head Art Direction), So Young Jang (Head Sculpt)",
        imgProduct1: "/img/ANAKIN_SKYWAKER1.jpg",
        imgProduct2: "/img/ANAKIN_SKYWAKER2.jpg",
        imgProduct3: "/img/ANAKIN_SKYWAKER3.jpg",
        imgProduct4: "/img/ANAKIN_SKYWAKER4.jpg",
        imgProduct5: "/img/ANAKIN_SKYWAKER5.jpg",
        preview: "Jabba the Hutt's™ kidnapped son is being held in a B'omarr™ Monastery built on top of a cliff. Anakin Skywalker™ begins the difficult ascent with battle droids firing down on him. So he makes a daring move and leaps onto a STAP, throws the battle droid from the vehicle, and races up the sheer wall. In the expansion of our Star Wars collectible series, Sideshow and Hot Toys present the Anakin Skywalker Sixth Scale Collectible Figure from Star Wars: The Clone Wars™ Masterfully crafted based on the appearance of Anakin Skywalker in highly-acclaimed animation series, the sixth scale collectible figure features a head sculpt with striking likesness, finely tailored costume, and a set of beautifully designed armor guards for alternative styles. His signature LED light-up lightsaber, a number of interchangeable hands, a thermal detonator, a hologram projector, and several hologram figures representing Ahsoka Tano™, Yoda™, and Obi-Wan Kenobi™ round out the set so you can take on the droid armies. This new Anakin Skywalker collectible figure will surely be a phenomenal masterpiece to add to any Star Wars collection!"
    },
    {
        id: 3,
        title: "boba fett (deluxe)",
        imgUrl: "/img/BOBA_FETT.png",
        size: "Sixth Scale Figure Set",
        price: 500,
        brand: "Star Wars",
        character: "Boba Fett",
        manufacturer: "Hot Toys",
        type: "Action FigureSixth>Scale Figure Set",
        genre: "Sci-fi>Pop Culture",
        artists: "Unknown",
        imgProduct1: "/img/BOBA_FETT1.jpg",
        imgProduct2: "/img/BOBA_FETT2.jpg",
        imgProduct3: "/img/BOBA_FETT3.jpg",
        imgProduct4: "/img/BOBA_FETT4.jpg",
        imgProduct5: "/img/BOBA_FETT5.jpg",
        preview: "“I'm a simple man making his way through the galaxy. Like my father before me.”  Star Wars™ fans were overjoyed to witness the return of Boba Fett, one of the most feared characters in the Star Wars galaxy! Thought to have met his demise in the terrifying Sarlacc pit on Tatooine™, Boba Fett is striking back. In exchange for his legacy armor from the possession of the Mandalorian, Boba Fett ensured the Child's safety and proved to be a formidable ally in Din Djarin'''s™ rescue of the mysterious alien foundling. Sideshow and Hot Toys are elated to expand the Star Wars collectible series with the Boba Fett (Deluxe Version) Sixth Scale Collectible Set, featuring the appearance of the formidable bounty hunter in a black robe and in his iconic armor! The armored Boba Fett figure features a meticulously crafted Mandalorian helmet and armor with distressed effects, his iconic jetpack with a detachable rocket and firing effect, weapon firing effects, a blaster, a chain code effect accessory, and a rocky diorama display stand! The Deluxe Version depicts Boba Fett's appearance before the retrieval of his armor and highlights include a newly developed head sculpt with stunning likeness, masterfully tailored black robe outfit, a gaffi stick, a cycler rifle, a damaged stormtrooper helmet, and a uniquely styled rocky diorama display stand. The Boba Fett collectible figure set (Deluxe Version) from The Mandalorian will be a legendary enhancement to any Star Wars collectible figures display!"
    },
    {
        id: 4,
        title: "obi-wan kenobi",
        imgUrl: "/img/OBI-WAN_KENOBI.png",
        size: "Sixth Scale Figure Set",
        price: 260,
        brand: "Star Wars",
        character: "Obi-Wan Kenobi",
        manufacturer: "Sideshow Collectibles",
        type: "Action Figure>Sixth Scale Figure",
        genre: "Sci-fi, Pop Culture, Action Adventure",
        artists: "Matt Black (Sculpt), Narae (Sculpt), Wan Lee (Paint), Namhoon Kim (Paint), Mijin Namgung (Costume Fabrication), The Sideshow Design and Development Team (Design) (Development)",
        imgProduct1: "/img/OBI-WAN_KENOBI1.jpg",
        imgProduct2: "/img/OBI-WAN_KENOBI2.jpg",
        imgProduct3: "/img/OBI-WAN_KENOBI3.jpg",
        imgProduct4: "/img/OBI-WAN_KENOBI4.jpg",
        imgProduct5: "/img/OBI-WAN_KENOBI5.jpg",
        preview: "“A great leap forward often requires first taking two steps back.” Sideshow presents the Obi-Wan Kenobi™ Sixth Scale Figure, inspired by the character's iconic animated appearance in Star Wars™: The Clone Wars. The Obi-Wan Kenobi Sixth Scale Figure captures the Jedi Knight's distinct design from the fan-favorite animated series The Clone Wars, as he works to keep the galactic peace alongside the Jedi Order. This articulated figure features a stylized headsculpt and a carefully tailored fabric costume consisting of a Jedi robe, tunic, undershirt, tabards, pants, a sash, a belt with sculpted accessories, and sculpted boots and gauntlets to create his signature uniformed look.  The Obi-Wan Kenobi Sixth Scale Figure includes a number of stylized hands and swap-out accessories to give collectors a wide range of display options for the Jedi general. Obi-Wan Kenobi comes with four pairs of stylized hands including a pair of grip hands, a pair of neutral hands, a pair of force hands, and a pair of fists for a wide variety of gestures and pose combinations. In addition, he comes with both a lightsaber hilt and lightsaber with its blue tapered blade unleashed for battle action. Finally, Obi-Wan includes a holoprojector accessory with a sculpted Commander Cody™ hologram for communicating with the loyal Clone Trooper. Take charge of your Star Wars collectibles and recruit the Obi-Wan Kenobi Sixth Scale Figure today!"
    },
    {
        id: 5,
        title: "general grievous",
        imgUrl: "/img/GENERAL_GRIEVOUS.png",
        size: "Premium Format™ Figure",
        price: 905, 
        brand: "Star Wars",
        character: "General Grievous",
        manufacturer: "Sideshow Collectibles",
        type: "Figure>Premium Format™ Figure",
        genre: "Sci-fi, Pop Culture, Action Adventure",
        artists: "Aaron McNaught (Sculpt), Matt Black (Design), Casey Love (Paint), The Sideshow Design and Development Team (Design) (Development)",
        imgProduct1: "/img/GENERAL_GRIEVOUS1.jpg",
        imgProduct2: "/img/GENERAL_GRIEVOUS2.jpg",
        imgProduct3: "/img/GENERAL_GRIEVOUS3.jpg",
        imgProduct4: "/img/GENERAL_GRIEVOUS4.jpg",
        imgProduct5: "/img/GENERAL_GRIEVOUS5.jpg",
        preview: "“I do not care about your Republic. I only live to see you DIE!” Sideshow presents the General Grievous™ Premium Format™ Figure, a ruthless strategist ready to take the lead of your Star Wars™ collectibles. The General Grievous Premium Format Figure measures 29” tall and 20 wide as the Separatist cyborg battles his enemies atop the wreckage of a starship-themed base. Trained in the art of the lightsaber duel, he draws the weapons of four fallen Jedi to lead his droid armies to victory in the Clone Wars conflict. The General Grievous Premium Format Figure is a mixed media collectible featuring a detailed sculpted figure and base as well as a removable fully fabric cape, which features an exterior gray fabric, red inner lining, and internal wiring in the hem allowing you to pose it dynamically to enhance the battle scene. The general's complex technological body is carefully sculpted to capture every detail of this iconic Star Wars character, with weathering on his white armored elements and his segmented arms split into an intimidating four-handed configuration. Each of the four lightsabers he holds has a clear green or blue blade in the hilt, creating the imposing silhouette General Grievous is known for across the galaxy. A fine addition to your collection — bring home the General Grievous Premium Format Figure today!"
    },
    {
        id: 6,
        title: "scout trooper",
        imgUrl: "/img/SCOUT_TROOPER.png",
        size: "Sixth Scale Figure",
        price: 225, 
        brand: "Star Wars",
        character: "Scout Trooper",
        manufacturer: "Hot Toys",
        type: "Action Figure>Sixth Scale Figure",
        genre: "Sci-fi,Pop Culture",
        artists: "Lok Ho (Paint), JC. Hong (Art Direction)",
        imgProduct1: "/img/SCOUT_TROOPER1.jpg",
        imgProduct2: "/img/SCOUT_TROOPER2.jpg",
        imgProduct3: "/img/SCOUT_TROOPER3.jpg",
        imgProduct4: "/img/SCOUT_TROOPER4.jpg",
        imgProduct5: "/img/SCOUT_TROOPER5.jpg",
        preview: "Scout Troopers were lightly armored compared with other Stormtroopers, which allowed them to move more quickly and easily in a range of environments. They were also trained for more independence and adaptability than most Imperial troops. The Empire used scout troopers for a range of missions, including reconnaissance and infiltration, Sideshow and Hot Toys are excited to continue expanding The Mandalorian collectible series and introduce the sixth scale Scout Trooper collectible figure from the highly acclaimed live-action series! , The highly-accurate Star Wars figure is skillfully crafted based on the appearance of the Imperial Scout Trooper in The Mandalorian. Featuring greatly detailed helmet and armor with astonishing weathering effects, a fabric bodysuit, a blaster rifle, and a figure stand!, Enlist the Scout Trooper sixth scale collectible figure now for your Star Wars collection."
    },
    {
        id: 7,
        title: "han solo",
        imgUrl: "/img/HAN_SOLO.png",
        size: "Sixth Scale Figure",
        price: 290,
        brand: "Star Wars",
        character: "Han Solo",
        manufacturer: "Hot Toys",
        type: "Action Figure>Sixth Scale Figure",
        genre: "Sci-fi, Pop Culture",
        artists: "Lok Ho (Paint), JC. Hong (Art Direction)",
        imgProduct1: "/img/HAN_SOLO1.jpg",
        imgProduct2: "/img/HAN_SOLO2.jpg",
        imgProduct3: "/img/HAN_SOLO3.jpg",
        imgProduct4: "/img/HAN_SOLO4.jpg",
        imgProduct5: "/img/HAN_SOLO5.jpg",
        preview: "Han Solo rose from an impoverished childhood on the mean streets of Corellia to become one of the heroes of the Rebel Alliance. As captain of the Millennium Falcon, Han and his co-pilot Chewbacca came to believe in the cause of galactic freedom, joining Luke Skywalker and Princess Leia Organa in the fight against the Empire. Sideshow and Hot Toys is very excited to officially present the brand new Han Solo Sixth Scale Figure based on the monumental Star Wars: Return Of The Jedi! The highly-accurate Han Solo collectible figure is skillfully crafted based on his appearance in the movie. It features a stunning head sculpt with great likeness and rotatable eyeballs, a finely tailored outfit with a camouflage coat, a blaster, and an Endor-themed environmental figure base! This Han Solo Sixth Scale Collectible Figure will be perfect for any Star Wars collectible fans’ collection!"
    },
    {
        id: 8,
        title: "darth vader",
        imgUrl: "/img/DARTH_VADER2.png",
        size: "Sixth Scale Figure",
        price: 245,
        brand: "Star Wars",
        character: "Darth Vader",
        manufacturer: "Sideshow Collectibles",
        type: "Action Figure>Sixth Scale Figure",
        genre: "Sci-fi, Pop Culture",
        artists: "Dave Kawano (Sculpt), Adrienne Smith (Sculpt), Bernardo Esquivel (Paint), Mijin Namgung (Costume), The Sideshow Design and Development Team",
        imgProduct1: "/img/DARTH_VADER21.jpg",
        imgProduct2: "/img/DARTH_VADER22.jpg",
        imgProduct3: "/img/DARTH_VADER23.jpg",
        imgProduct4: "/img/DARTH_VADER24.jpg",
        imgProduct5: "/img/DARTH_VADER25.jpg",
        preview: "Joining the Star Wars collectibles sixth scale figure collection, Sideshow Collectibles is proud to present the Darth Vader Sixth Scale Figure. Recreate every memorable scene with this Vader figure, crafted on a fully articulated body with finely tailored costume and body armor elements, and featuring newly sculpted elements, new costume, new lightsaber blade and our hexagonal figure base.  Star Wars fans don't miss your chance to add this Sith Lord to your most impressive Star Wars Figure collection!"
    },
    {
        id: 9,
        title: "purge trooper",
        imgUrl: "/img/PURGE_TROOPER.png",
        size: "Sixth Scale Figure",
        price: 240,
        brand: "Star Wars",
        character: "Stormtrooper, Purge Trooper",
        manufacturer: "Hot Toys",
        type: "Action Figure>Sixth Scale Figure",
        genre: "Sci-fi Pop>Culture",
        artists: "Unknown",
        imgProduct1: "/img/PURGE_TROOPER1.jpg",
        imgProduct2: "/img/PURGE_TROOPER2.jpg",
        imgProduct3: "/img/PURGE_TROOPER3.jpg",
        imgProduct4: "/img/PURGE_TROOPER4.jpg",
        imgProduct5: "/img/PURGE_TROOPER5.jpg",
        preview: "Purge troopers are a specialized class of Imperial soldier trained and equipped to assist the Inquisitors™ in hunting down Jedi™ and other Force-sensitive beings who threaten the Empire. Borrowing tactics and methods first used by the Republic soldiers that accompanied Jedi generals during the Clone Wars, this elite group is few in number and keeps out of the public eye. , Following the finale of the Obi-Wan Kenobi live-action series, Sideshow and Hot Toys are pleased to present the Purge Trooper Sixth Scale Collectible Figure, The collectible figure is meticulously crafted with a detailed helmet and armor in black and red paint applications, a form-fitting under-suit, a red pauldron, a blaster rifle, and a figure base! , This new specialized Stormtrooper figure will be an excellent addition to your Star Wars collectibles display!"
    }
]

export default data2